### ISSUE TITLE
phy

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#23]
https://github.com/cortex-lab/phy

[https://github.com/cortex-lab/phy/blob/master/environment.yml](https://github.com/cortex-lab/phy/blob/master/environment.yml):
```yaml
name: phy2
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - git
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - pyopengl
  - pyqtwebengine
  - pytest
  - qtconsole
  - requests
  - responses
  - traitlets
  - dask
  - cython
  - pillow
  - scikit-learn
  - joblib
  - pip:
    - git+https://github.com/cortex-lab/phy.git
```
